2019-05-08 17:59:02,696 [DEBUG] Using GPU 0
2019-05-08 17:59:02,745 [DEBUG] CACHEDIR=/home/thinh/.cache/matplotlib
2019-05-08 17:59:02,748 [DEBUG] Using fontManager instance from /home/thinh/.cache/matplotlib/fontlist-v300.json
2019-05-08 17:59:02,869 [DEBUG] Loaded backend agg version unknown.
2019-05-08 17:59:10,478 [INFO] ==> VIDEO_ROOT_PATH/UCSD_ped1/testing_h5_t0/UCSD_ped1_01.h5
2019-05-08 17:59:10,479 [DEBUG] Predicting using logs/UCSD_ped1/jobs/f5846318-6990-4622-b584-ececf33a54d7/model_snapshot_e298_0.003159.h5
2019-05-08 17:59:30,957 [CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/thinh/Downloads/pycharm-community-2018.3.5/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/thinh/github/anomaly-detection-and-localization/start_test.py", line 73, in <module>
    visualize_score=True, visualize_frame=True)
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 639, in test
    save_anomaly_score(anomaly_score(total_err),
  File "/home/thinh/github/anomaly-detection-and-localization/classifier.py", line 565, in anomaly_score
    score_vid = raw_frame_cost_vid - min(raw_frame_cost_vid)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
